### ISSUE TITLE
Poco Launcher support

### ISSUE THREAD

**Issue by marco-tls** [danimahardhika/candybar-library#157]
Hello, I've built 2 icon packs based on Candy bar library, they perfectly works on the majority of the launchers except Poco Launcher (ported on NON-MIUI phones).
Icon packs are correctly shown in the list of available icon packs to be installed (so I assume that Poco Launcher rscognizes the icon packs) but when applying them, icons are not applied.
I suppose there should be some code or tags to be added, or updated, but I can't figure out which ones.

Can you please share with me this info?
Please note that I've found out other icon packs based on CandyBar that actually work with Poco Launcher, so I'm sure that a solution exists, just need to know which one.

Thank you for letting this project to be real, and for the wonderful job done.
Regards
Marco

**Comment by benneb1020301** [comment]
Actually I found out why that happened and I fixed it.

Apparently the donations and license check was turned on while I didn't add
any info for them

**Comment by marco-tls** [comment]
Thank you but I honestly think you did not get the point. Everything works, except in Poco Launcher. Do you have suggestions on how to make it work for that specific Launcher?

**Comment by qigeco** [comment]
The same ,how to make it work for the Poco Launcher?

**Comment by srvraj311** [comment]
Any solution to this? Because i still have the same problem.

**Comment by walrus543** [comment]
You should switch to the fork: https://github.com/zixpo/candybar-sample
and join our TG group: https://t.me/candybar_unofficial
